import React from 'react';
import { AlertTriangle } from 'lucide-react';
import { Card } from '@/components/ui/card';

export const LegalDisclaimer: React.FC = () => {
  return (
    <Card className="relative overflow-hidden border-2 border-amber-300 dark:border-amber-700 bg-gradient-to-br from-amber-50 via-yellow-50 to-amber-50 dark:from-amber-950 dark:via-yellow-950 dark:to-amber-950 shadow-lg">
      {/* Warning stripe pattern */}
      <div className="absolute top-0 left-0 right-0 h-2 bg-gradient-to-r from-amber-500 via-yellow-500 to-amber-500" />
      
      <div className="p-6 space-y-4">
        {/* Header */}
        <div className="flex items-center gap-3 pb-3 border-b-2 border-amber-200 dark:border-amber-800">
          <div className="w-10 h-10 bg-gradient-to-br from-amber-500 to-orange-500 rounded-xl flex items-center justify-center shadow-md">
            <AlertTriangle className="h-6 w-6 text-white" strokeWidth={2.5} />
          </div>
          <h3 className="text-xl font-bold text-amber-900 dark:text-amber-100">
            Mandatory Legal Disclaimer
          </h3>
        </div>
        
        {/* Content */}
        <div className="space-y-3 text-sm leading-relaxed text-amber-900 dark:text-amber-100">
          <p className="font-semibold text-base">
            ⚠️ This analysis is generated by an AI system for informational purposes only
          </p>
          
          <div className="space-y-2 pl-4 border-l-4 border-amber-400 dark:border-amber-600">
            <p>
              <strong className="font-bold">Not Legal Advice:</strong> This directive does not constitute legal advice and should not be relied upon as a substitute for consultation with a qualified attorney.
            </p>
            
            <p>
              <strong className="font-bold">No Attorney-Client Relationship:</strong> Use of this system does not create an attorney-client relationship. Any information shared is not protected by attorney-client privilege.
            </p>
            
            <p>
              <strong className="font-bold">Accuracy Not Guaranteed:</strong> While efforts are made to provide accurate information, AI-generated content may contain errors, omissions, or outdated information. Always verify critical information with authoritative legal sources.
            </p>
            
            <p>
              <strong className="font-bold">Jurisdiction Specific:</strong> Laws vary by jurisdiction and change over time. This analysis may not reflect the most current legal developments or be applicable to your specific jurisdiction.
            </p>
            
            <p>
              <strong className="font-bold">Consult Licensed Attorney:</strong> For specific legal advice tailored to your situation, please consult with a licensed attorney in your jurisdiction who can review all relevant facts and circumstances.
            </p>
          </div>
          
          <div className="mt-4 p-4 bg-amber-100 dark:bg-amber-900/50 rounded-lg border-2 border-amber-300 dark:border-amber-700">
            <p className="font-bold text-center text-amber-900 dark:text-amber-100">
              By using this system, you acknowledge that you have read and understood this disclaimer.
            </p>
          </div>
        </div>
      </div>
    </Card>
  );
};
